class LocationData {
  static const Map<String, List<String>> regionsAndCities = {
    'Riyadh Region': [
      'Riyadh',
      'Al Majmaah',
      'Al Kharj',
      'Afif',
      'Az Zulfi',
      'Shaqra',
      'Ad Diriyah',
      'Dawadmi',
      'Al Muzahimiyah',
      'Rumah',
    ],
    'Makkah Province': [
      'Mecca',
      'Jeddah',
      'Taif',
      'Rabigh',
      'Khulais',
      'Ranyah',
      'Al Jumum',
      'Bahra',
      'Al Kamil',
      'Al Khurma',
    ],
    'Eastern Province': [
      'Dammam',
      'Al Khobar',
      'Dhahran',
      'Al Jubail',
      'Al Ahsa',
      'Qatif',
      'Hafr Al Batin',
      'Ras Tanura',
      'Al Nairyah',
      'Khafji',
    ],
    'Asir Province': [
      'Abha',
      'Khamis Mushait',
      'Najran',
      'Bisha',
      'Mahayel',
      'Sarat Abidah',
      'Balqarn',
      'Rijal Almaa',
      'Tanomah',
      'Ahad Rafidah',
    ],
    'Qassim Province': [
      'Buraydah',
      'Unaizah',
      'Ar Rass',
      'Al Mithnab',
      'Al Bukayriyah',
      'Riyadh Al Khabra',
      'Uyun Al Jiwa',
      'Al Shammasiyah',
      'Ad Dakhilah',
      'Dhariyah',
    ],
    'Hail Province': [
      'Hail',
      'Baqaa',
      'Al Ghazalah',
      'Ash Shinan',
      'As Sulaymi',
      'Al Hawiyah',
      'Ash Shamli',
      'Umm Al Qulban',
      'Al Kahfah',
      'Ash Shafiyah',
    ],
    'Tabuk Province': [
      'Tabuk',
      'Umluj',
      'Al Wajh',
      'Duba',
      'Tayma',
      'Al Bad',
      'Haql',
      'Sharma',
      'Al Uwayqilah',
      'Bir Ibn Hirmas',
    ],
    'Northern Borders Province': [
      'Arar',
      'Rafha',
      'Turayf',
      'Al Uwayqilah',
      'Hazm Al Jalamid',
      'Ash Shuwayhitiyah',
      'Dawmat Al Jandal',
      'Suwayr',
      'Busayta',
      'Al Nazala',
    ],
    'Jazan Province': [
      'Jazan',
      'Sabya',
      'Abu Arish',
      'Samtah',
      'Farasan',
      'Al Dair',
      'Baysh',
      'Ad Darb',
      'Ahad Al Masarihah',
      'Al Aridah',
    ],
    'Najran Province': [
      'Najran',
      'Sharourah',
      'Habuna',
      'Badr Al Janub',
      'Yadmah',
      'Khubash',
      'Thar',
      'Hubuna',
      'Al Kharkhir',
      'Zurba',
    ],
    'Al Bahah Province': [
      'Al Bahah',
      'Baljurashi',
      'Al Mandaq',
      'Qilwah',
      'Al Aqiq',
      'Al Makhwah',
      'Bani Hassan',
      'Al Qura',
      'Ghamid Al Zinad',
      'Al Hajrah',
    ],
    'Al Jouf Province': [
      'Sakaka',
      'Qurayyat',
      'Tubarjal',
      'Dawmat Al Jandal',
      'Tabarjal',
      'Suwayr',
      'Al Hazm',
      'Az Zaytah',
      'Busayta',
      'Al Ithilah',
    ],
    'Madinah Province': [
      'Medina',
      'Yanbu',
      'Al Ula',
      'Badr',
      'Khaybar',
      'Al Mahd',
      'Wadi Al Fara',
      'Al Hanakiyah',
      'Al Ais',
      'Mahd Ad Dahab',
    ],
  };

  static const Map<String, List<String>> cityDistricts = {
    // Riyadh districts (expanded)
    'Riyadh': [
      'Al Olaya',
      'Al Malaz',
      'Al Naseem',
      'Al Sulaimaniyah',
      'King Fahd District',
      'Al Mohammadiyah',
      'Al Rawdah',
      'Al Andalus',
      'Al Maather',
      'Al Nakheel',
      'Al Izdihar',
      'Al Sahafa',
      'Al Yasmeen',
      'Al Narjis',
      'Al Woroud',
      'Al Takhassusi',
      'Diplomatic Quarter',
      'King Abdullah Financial District',
      'Al Aqiq',
      'Al Hamra',
      'Al Aziziyah',
      'Al Faisaliyah',
      'Al Khalidiyah',
      'Al Manar',
      'Al Murjan',
      'Al Muzdalifah',
      'Al Qadisiyah',
      'Al Rahmaniyah',
      'Al Rimal',
      'Al Shams',
      'Al Shifa',
      'Al Wadi',
      'Al Yasmin',
      'Al Zahra',
      'Ar Rabwah',
      'As Safarat',
      'As Sulay',
      'At Takhassusi',
      'Dhahrat Laban',
      'Ghirnatah',
      'Hittin',
      'King Saud University',
      'Laban',
      'Makkah Road',
      'Mishrifah',
      'Qurtubah',
      'Tuwaiq',
      'Ulaya',
      'Umm Al Hamam',
      'Wasat Al Balad',
    ],

    // Jeddah districts (expanded)
    'Jeddah': [
      'Al Hamra',
      'Al Sharafiyah',
      'Al Balad',
      'Al Salamah',
      'Al Rawdah',
      'Al Zahra',
      'Al Andalus',
      'Al Manar',
      'Al Faisaliyah',
      'Al Khalidiyah',
      'Al Corniche',
      'Al Aziziyah',
      'Al Samer',
      'Al Muhammadiyah',
      'Al Safa',
      'Al Marwah',
      'Al Naeem',
      'Al Shati',
      'Al Basateen',
      'Al Masakin',
      'Al Baghdadiyah',
      'Al Bawadi',
      'Al Bughaddadiyah',
      'Al Candarah',
      'Al Firdaus',
      'Al Hindawiyah',
      'Al Iskan',
      'Al Jamiah',
      'Al Khobar',
      'Al Lulu',
      'Al Mahjar',
      'Al Makarunah',
      'Al Muntazahat',
      'Al Nuzlah Al Yamaniyah',
      'Al Quwayiyah',
      'Al Ruwais',
      'Al Sabeel',
      'Al Thalatha',
      'Al Waha',
      'An Nasim',
      'Ar Rihab',
      'As Sulaymaniyah',
      'Ash Sharafeyah',
      'Briman',
      'Madaen Al Fahd',
      'Miskak',
      'Mushrifah',
      'Obhur Al Shamaliyah',
      'Obhur Al Janubiyah',
    ],

    // Dammam districts (expanded)
    'Dammam': [
      'Al Faisaliyah',
      'Al Mazruiyah',
      'Al Shatea',
      'Al Jalawiyah',
      'Al Badiyah',
      'Al Anoud',
      'Al Doha',
      'Al Murjan',
      'Al Noor',
      'Al Shurouq',
      'Al Ferdous',
      'Al Mohammadiyah',
      'Al Rawdah',
      'Al Andalus',
      'Al Salam',
      'Al Khalij',
      'Al Corniche',
      'Al Nakheel',
      'Al Tubishi',
      'Al Adamah',
      'Al Aziziyah',
      'Al Hamra',
      'Al Khalidiyah',
      'Al Manar',
      'Al Nasiriyah',
      'Al Qadisiyah',
      'Al Rakah Al Janubiyah',
      'Al Rakah Al Shamaliyah',
      'Al Reef',
      'Al Saif',
      'Al Salam',
      'Al Ulaya',
      'Al Yamama',
      'Al Zuhur',
      'As Sadafah',
      'As Shulla',
      'At Tubishi',
      'Badr',
      'Darin',
      'Dhahran Al Janub',
      'Happy Land',
      'Imam Abdulrahman Bin Faisal University',
      'King Fahd University',
      'Madinat Al Ummal',
      'Uhud',
    ],

    // Al Khobar districts (expanded)
    'Al Khobar': [
      'Al Aqrabiyah',
      'Al Ulaya',
      'Al Thuqbah',
      'Al Rakah',
      'Al Jisr',
      'Al Hizam Al Akhdar',
      'Al Corniche',
      'Al Bandariyah',
      'Al Olaya',
      'Al Khobar Al Shamaliyah',
      'Al Khobar Al Janubiyah',
      'Al Manar',
      'Al Qadisiyah',
      'Al Khuzama',
      'Dana',
      'Al Yarmouk',
      'Al Rawabi',
      'Al Doha',
      'Al Khalidiyah',
      'Al Aziziyah',
      'Al Iskan',
      'Al Mohammadiyah',
      'Al Rawdah',
      'Al Salam',
      'Al Shati',
      'Al Sultani',
      'Al Tawfiq',
      'Al Uyun',
      'Al Waha',
      'Ar Rakah',
      'As Salam',
      'At Tubishi',
      'Bayat Al Watan',
      'Corniche Road',
      'Dana District',
      'Dhahran',
      'Half Moon Bay',
      'King Fahd Causeway',
      'Prince Turkey Street',
      'Sitteen Street',
    ],

    // Mecca districts (expanded)
    'Mecca': [
      'Al Haram',
      'Ajyad',
      'Al Misfalah',
      'Al Rusaifah',
      'Al Maabdah',
      'Jabal Omar',
      'Al Shamiyah',
      'Al Ghassalah',
      'Al Tandabawi',
      'Al Kakiyah',
      'Al Masjid Al Haram',
      'Al Shabikah',
      'Jabal Al Nour',
      'Al Khalidiyah',
      'Al Awali',
      'Al Zahir',
      'Al Shubaikah',
      'Wadi Jalil',
      'Al Hijrah',
      'Al Nuzha',
      'Al Aziziyah',
      'Al Haram Ash Sharif',
      'Al Jumrah',
      'Al Khalil',
      'Al Mahbas',
      'Al Marwah',
      'Al Mas\'a',
      'Al Multazam',
      'Al Qishashiyah',
      'Al Safaa',
      'Al Taqwa',
      'Al Umrah',
      'As Salam',
      'Bab Al Majidi',
      'Jarwal',
      'Kudai',
      'Mina',
      'Muzdalifah',
      'Shisha',
      'Umm Al Jud',
    ],

    // Al Majmaah districts
    'Al Majmaah': [
      'Al Markaz',
      'Al Andalus',
      'Al Faisaliyah',
      'Al Khalidiyah',
      'Al Rawdah',
      'Al Salam',
      'Al Aziziyah',
      'Al Mohammadiyah',
      'Al Wadi',
      'Al Naseem',
      'Al Manar',
      'Al Wurud',
      'As Salam',
      'King Saud University Campus',
      'University District',
    ],

    // Al Kharj districts
    'Al Kharj': [
      'Al Markaz',
      'Al Andalus',
      'Al Faisaliyah',
      'Al Khalidiyah',
      'Al Rawdah',
      'Al Salam',
      'Al Aziziyah',
      'Al Mohammadiyah',
      'Al Wadi',
      'Al Naseem',
      'Al Manar',
      'Al Wurud',
      'As Salam',
      'Industrial Area',
      'Agricultural Area',
    ],

    // Taif districts (expanded)
    'Taif': [
      'Al Salamah',
      'Al Faisaliyah',
      'Al Andalus',
      'Al Naseem',
      'Al Shafa',
      'Al Hada',
      'Al Rudaf',
      'Al Hawiyah',
      'Okaz',
      'Al Khalidiyah',
      'Al Aziziyah',
      'Al Rawdah',
      'Al Manar',
      'Al Wadi',
      'Al Sharqiyah',
      'Al Gharbiyah',
      'Al Wassat',
      'Al Jizan',
      'Al Qim',
      'Souq Okaz',
      'Al Mohammadiyah',
      'Al Nakheel',
      'Al Salam',
      'Al Wurud',
      'Al Yasmeen',
      'As Sayl',
      'Arafat Road',
      'Old Taif',
      'Rose Garden',
      'Shubra',
      'Wadi Waj',
    ],

    // Abha districts (expanded)
    'Abha': [
      'Al Manhal',
      'Al Muftaha',
      'Al Qabil',
      'Al Dabab',
      'Al Mahalah',
      'As Sadd',
      'Al Khalidiyah',
      'Al Andalus',
      'Al Shafa',
      'Al Wurud',
      'Al Salam',
      'Al Manar',
      'Al Nakheel',
      'Shadah',
      'Al Malak Abdul Aziz',
      'Al Aziziyah',
      'Al Rawdah',
      'Al Naseem',
      'Al Wadi',
      'Khamis Mushait Road',
      'Al Faisaliyah',
      'Al Mohammadiyah',
      'Al Yasmeen',
      'Al Zahra',
      'Aseer National Park',
      'Green Mountain',
      'King Khalid University',
      'New Abha',
      'Old Abha',
      'Rijal Alma Village',
    ],

    // Buraydah districts (expanded)
    'Buraydah': [
      'Al Safra',
      'Al Nassim',
      'Al Iskan',
      'Al Salam',
      'Al Fayha',
      'Al Yelayel',
      'Al Rawdah',
      'Al Andalus',
      'Al Manar',
      'Al Khalidiyah',
      'Al Faisaliyah',
      'Al Aziziyah',
      'Al Mohammadiyah',
      'Al Wadi',
      'Al Sharq',
      'Al Gharb',
      'Al Shammal',
      'Al Janub',
      'Al Markaz',
      'Al Souq',
      'Al Nakheel',
      'Al Wurud',
      'Al Yasmeen',
      'Al Zahra',
      'As Suwaidi',
      'Date Palm Oasis',
      'Industrial City',
      'King Saud Road',
      'Old Buraydah',
      'Qassim University',
    ],

    // Unaizah districts
    'Unaizah': [
      'Al Markaz',
      'Al Andalus',
      'Al Faisaliyah',
      'Al Khalidiyah',
      'Al Rawdah',
      'Al Salam',
      'Al Aziziyah',
      'Al Mohammadiyah',
      'Al Wadi',
      'Al Naseem',
      'Al Manar',
      'Al Wurud',
      'As Salam',
      'Heritage Village',
      'Industrial Area',
    ],

    // Medina districts (expanded)
    'Medina': [
      'Al Haram',
      'Quba',
      'Al Anbariyah',
      'Al Aziziyah',
      'Al Khalidiyah',
      'Al Faisaliyah',
      'Al Andalus',
      'Al Rawdah',
      'Al Manar',
      'Al Salam',
      'Al Nakheel',
      'Al Shurta',
      'Al Mahatta',
      'Al Qiblatayn',
      'Uhud',
      'Al Ranuna',
      'Al Awali',
      'Al Jumuah',
      'Al Thaniyah',
      'Al Dar',
      'Al Mohammadiyah',
      'Al Naseem',
      'Al Wurud',
      'Al Yasmeen',
      'Al Zahra',
      'As Salam',
      'Islamic University',
      'King Abdulaziz Road',
      'Masjid Nabawi',
      'Prince Naif Road',
    ],

    // Yanbu districts (expanded)
    'Yanbu': [
      'Al Balad',
      'Al Sinaiyah',
      'Al Shurouq',
      'Al Salam',
      'Al Khalidiyah',
      'Al Faisaliyah',
      'Al Andalus',
      'Al Rawdah',
      'Al Corniche',
      'Al Mahatta',
      'Al Markaz',
      'Al Nakheel',
      'Al Aziziyah',
      'Al Manar',
      'Al Safa',
      'Al Marwah',
      'Al Dahab',
      'Al Lulu',
      'Al Murjan',
      'Al Bahar',
      'Al Mohammadiyah',
      'Al Naseem',
      'Al Wurud',
      'Al Yasmeen',
      'Industrial City',
      'Petrochemical Complex',
      'Royal Commission',
      'Yanbu University College',
    ],

    // Tabuk districts (expanded)
    'Tabuk': [
      'Al Khalidiyah',
      'Al Faisaliyah',
      'Al Andalus',
      'Al Rawdah',
      'Al Salam',
      'Al Manar',
      'Al Aziziyah',
      'Al Mohammadiyah',
      'Al Wadi',
      'Al Markaz',
      'Al Shammal',
      'Al Janub',
      'Al Sharq',
      'Al Gharb',
      'Al Souq',
      'Al Mahatta',
      'Al Shurta',
      'Al Nakheel',
      'Al Naseem',
      'Al Wurud',
      'Airport District',
      'Industrial Area',
      'King Khalid Road',
      'Old Tabuk',
      'University of Tabuk',
    ],

    // Hail districts (expanded)
    'Hail': [
      'Al Khalidiyah',
      'Al Faisaliyah',
      'Al Andalus',
      'Al Rawdah',
      'Al Salam',
      'Al Manar',
      'Al Aziziyah',
      'Al Mohammadiyah',
      'Al Wadi',
      'Al Markaz',
      'Al Shammal',
      'Al Janub',
      'Al Sharq',
      'Al Gharb',
      'Al Souq',
      'Al Mahatta',
      'Al Shurta',
      'Al Nakheel',
      'Al Naseem',
      'Al Wurud',
      'A\'arif Fort',
      'Barzan Palace',
      'Hail University',
      'Qishlah Palace',
      'Traditional Market',
    ],

    // Jazan districts (expanded)
    'Jazan': [
      'Al Khalidiyah',
      'Al Faisaliyah',
      'Al Andalus',
      'Al Rawdah',
      'Al Salam',
      'Al Manar',
      'Al Aziziyah',
      'Al Mohammadiyah',
      'Al Wadi',
      'Al Markaz',
      'Al Corniche',
      'Al Mahatta',
      'Al Shurta',
      'Al Nakheel',
      'Al Naseem',
      'Al Wurud',
      'Al Bahar',
      'Al Souq',
      'Al Shammal',
      'Al Janub',
      'Corniche Road',
      'Jazan Economic City',
      'Jazan University',
      'Port Area',
      'Traditional Souq',
    ],

    // Najran districts (expanded)
    'Najran': [
      'Al Khalidiyah',
      'Al Faisaliyah',
      'Al Andalus',
      'Al Rawdah',
      'Al Salam',
      'Al Manar',
      'Al Aziziyah',
      'Al Mohammadiyah',
      'Al Wadi',
      'Al Markaz',
      'Al Shammal',
      'Al Janub',
      'Al Sharq',
      'Al Gharb',
      'Al Souq',
      'Al Mahatta',
      'Al Shurta',
      'Al Nakheel',
      'Al Naseem',
      'Al Wurud',
      'Al Ukhdood',
      'Heritage Village',
      'Najran University',
      'Old Najran',
      'Traditional Architecture District',
    ],

    // Al Bahah districts (expanded)
    'Al Bahah': [
      'Al Khalidiyah',
      'Al Faisaliyah',
      'Al Andalus',
      'Al Rawdah',
      'Al Salam',
      'Al Manar',
      'Al Aziziyah',
      'Al Mohammadiyah',
      'Al Wadi',
      'Al Markaz',
      'Al Shammal',
      'Al Janub',
      'Al Sharq',
      'Al Gharb',
      'Al Souq',
      'Al Mahatta',
      'Al Shurta',
      'Al Nakheel',
      'Al Naseem',
      'Al Wurud',
      'Al Sarawat Mountains',
      'Forest Park',
      'Raghadan Forest',
      'Traditional Villages',
      'University District',
    ],

    // Sakaka districts (expanded)
    'Sakaka': [
      'Al Khalidiyah',
      'Al Faisaliyah',
      'Al Andalus',
      'Al Rawdah',
      'Al Salam',
      'Al Manar',
      'Al Aziziyah',
      'Al Mohammadiyah',
      'Al Wadi',
      'Al Markaz',
      'Al Shammal',
      'Al Janub',
      'Al Sharq',
      'Al Gharb',
      'Al Souq',
      'Al Mahatta',
      'Al Shurta',
      'Al Nakheel',
      'Al Naseem',
      'Al Wurud',
      'Airport District',
      'Government District',
      'Industrial Area',
      'Jouf University',
      'Old Town',
    ],

    // Arar districts (expanded)
    'Arar': [
      'Al Khalidiyah',
      'Al Faisaliyah',
      'Al Andalus',
      'Al Rawdah',
      'Al Salam',
      'Al Manar',
      'Al Aziziyah',
      'Al Mohammadiyah',
      'Al Wadi',
      'Al Markaz',
      'Al Shammal',
      'Al Janub',
      'Al Sharq',
      'Al Gharb',
      'Al Souq',
      'Al Mahatta',
      'Al Shurta',
      'Al Nakheel',
      'Al Naseem',
      'Al Wurud',
      'Border District',
      'Commercial Center',
      'Government Complex',
      'Northern Border University',
      'Residential Area',
    ],

    // Additional major cities with districts

    // Dhahran districts
    'Dhahran': [
      'Al Doha',
      'Al Faisaliyah',
      'Al Khalidiyah',
      'Al Rawdah',
      'Al Salam',
      'Al Thuqbah',
      'Aramco Compound',
      'King Fahd University',
      'Residential District',
      'Techno Valley',
      'University Area',
    ],

    // Al Jubail districts
    'Al Jubail': [
      'Al Balad',
      'Al Dana',
      'Al Deffi',
      'Al Fanateer',
      'Al Huwailat',
      'Al Watani',
      'Industrial City',
      'Jubail Commercial Port',
      'Madinat Al Jubail As Sinaiyah',
      'Royal Commission Area',
    ],

    // Al Ahsa districts
    'Al Ahsa': [
      'Al Hofuf',
      'Al Mubarraz',
      'Al Omran',
      'Al Qara',
      'Al Jafr',
      'Al Kilabiyah',
      'As Saalam',
      'Historic District',
      'Modern Al Ahsa',
      'Oasis Area',
    ],

    // Qatif districts
    'Qatif': [
      'Al Awjam',
      'Al Jish',
      'Al Qadih',
      'Al Tubi',
      'Anak',
      'Safwa',
      'Saihat',
      'Tarout',
      'Um Al Sahek',
      'Coastal Area',
    ],

    // Khamis Mushait districts
    'Khamis Mushait': [
      'Al Khalidiyah',
      'Al Faisaliyah',
      'Al Rawdah',
      'Al Salam',
      'Al Wadi',
      'King Khalid University',
      'Military Base Area',
      'New Khamis',
      'Old Khamis',
      'Shopping District',
    ],

    // Sabya districts
    'Sabya': [
      'Al Markaz',
      'Al Andalus',
      'Al Faisaliyah',
      'Al Khalidiyah',
      'Al Rawdah',
      'Al Salam',
      'Agricultural Area',
      'Coastal District',
      'Heritage Area',
      'Residential Zone',
    ],

    // Hafr Al Batin districts
    'Hafr Al Batin': [
      'Al Khalidiyah',
      'Al Faisaliyah',
      'Al Rawdah',
      'Al Salam',
      'Al Wadi',
      'Commercial Center',
      'Industrial Area',
      'King Fahd Road',
      'Military Zone',
      'University District',
    ],

    // Ar Rass districts
    'Ar Rass': [
      'Al Markaz',
      'Al Andalus',
      'Al Faisaliyah',
      'Al Khalidiyah',
      'Al Rawdah',
      'Al Salam',
      'Agricultural District',
      'Commercial Area',
      'Heritage Quarter',
      'Residential Zone',
    ],

    // Rafha districts
    'Rafha': [
      'Al Khalidiyah',
      'Al Faisaliyah',
      'Al Rawdah',
      'Al Salam',
      'Border Area',
      'Commercial District',
      'Government Complex',
      'Residential Area',
      'Traditional Quarter',
    ],

    // Turayf districts
    'Turayf': [
      'Al Khalidiyah',
      'Al Faisaliyah',
      'Al Rawdah',
      'Al Salam',
      'Border Crossing',
      'Commercial Zone',
      'Government Area',
      'Residential District',
      'Traditional Area',
    ],

    // Sharourah districts
    'Sharourah': [
      'Al Khalidiyah',
      'Al Faisaliyah',
      'Al Rawdah',
      'Al Salam',
      'Airport District',
      'Commercial Center',
      'Government Complex',
      'Industrial Area',
      'Residential Zone',
    ],

    // Al Ula districts
    'Al Ula': [
      'Al Khalidiyah',
      'Al Faisaliyah',
      'Al Rawdah',
      'Al Salam',
      'Heritage Area',
      'Hegra Archaeological Site',
      'Modern Al Ula',
      'Old Town',
      'Tourism District',
    ],

    // Qurayyat districts
    'Qurayyat': [
      'Al Khalidiyah',
      'Al Faisaliyah',
      'Al Rawdah',
      'Al Salam',
      'Agricultural Area',
      'Commercial District',
      'Government Zone',
      'Industrial Area',
      'Residential Quarter',
    ],

    // Baljurashi districts
    'Baljurashi': [
      'Al Khalidiyah',
      'Al Faisaliyah',
      'Al Rawdah',
      'Al Salam',
      'Forest Area',
      'Heritage Village',
      'Mountain District',
      'Tourism Zone',
      'Traditional Quarter',
    ],

    // Al Mandaq districts
    'Al Mandaq': [
      'Al Khalidiyah',
      'Al Faisaliyah',
      'Al Rawdah',
      'Al Salam',
      'Agricultural Area',
      'Heritage District',
      'Mountain Village',
      'Traditional Area',
      'Tourism Zone',
    ],
  };

  // Helper methods
  static List<String> getAllRegions() {
    return regionsAndCities.keys.toList()..sort();
  }

  static List<String> getCitiesForRegion(String region) {
    return regionsAndCities[region] ?? [];
  }

  static List<String> getDistrictsForCity(String city) {
    return cityDistricts[city] ?? [];
  }

  static bool isValidRegion(String region) {
    return regionsAndCities.containsKey(region);
  }

  static bool isValidCityInRegion(String city, String region) {
    final cities = getCitiesForRegion(region);
    return cities.contains(city);
  }

  static bool isValidDistrictInCity(String district, String city) {
    final districts = getDistrictsForCity(city);
    return districts.contains(district);
  }

  // Get region for a city (reverse lookup)
  static String? getRegionForCity(String city) {
    for (final entry in regionsAndCities.entries) {
      if (entry.value.contains(city)) {
        return entry.key;
      }
    }
    return null;
  }
}
