name: semester_student_ride_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+10

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Design Packages
  cupertino_icons: 
  flutter_screenutil: 
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  google_fonts: ^6.2.0
  image_cropper: ^9.1.0
  image_picker: ^1.1.2
  loading_animation_widget: ^1.3.0
  flutter_otp_text_field:
  time_picker_spinner_pop_up:
  carousel_slider: ^5.1.1

  # State Management Packages
  flutter_hooks: ^0.20.0
  hooks_riverpod: ^2.6.1
  go_router: ^14.2.9
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  freezed_annotation: ^2.4.4
  freezed:
  json_annotation: ^4.9.0
  flutter_datetime_picker_plus: ^2.2.0
  # package_info_plus: ^5.0.1
  
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.9

  # Firebase and Authentication Packages
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.7
  shared_preferences: ^2.2.3
  another_flushbar: ^1.12.30
  syncfusion_flutter_sliders:
  flutter_rating: ^2.0.2

  # Networking Packages
  http: ^1.2.2

  # Miscellaneous Packages
  flutter_native_splash: ^2.4.4
  persistent_bottom_nav_bar: ^6.2.1
  firebase_messaging: ^15.2.5
  flutter_local_notifications: ^19.4.2
  google_maps_flutter: ^2.5.3
  geolocator: ^10.1.0
  firebase_storage: ^12.4.5
  google_places_flutter: ^2.0.9 
  firebase_auth: ^5.5.3
  mailer: ^6.4.1
  permission_handler: ^11.3.0
  cloud_functions: ^5.5.1
  path_provider: ^2.1.2
  flutter_polyline_points: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  # Linting and Code Quality Packages
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.3.11
  build_runner: ^2.4.13
  json_serializable:

dependency_overrides:
  custom_lint_core: ^0.6.3
  rxdart: ^0.27.7
  platform: ^3.1.0
  intl: ^0.20.2

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/data/saudi_districts.json
    - assets/icons/
    - assets/images/
    - assets/logo/
    - assets/
