// Saudi Arabian cities data
class SaudiCities {
  static const List<String> cities = [
    'Riyadh',
    'Jeddah',
    'Mecca',
    'Medina',
    'Dammam',
    'Khobar',
    'Dhahran',
    'Jubail',
    'Tabuk',
    'Buraidah',
    'Khamis Mushait',
    'Hail',
    'Hafar Al-Batin',
    'Mubarak Al-Kabeer',
    'Hofuf',
    'Mubarraz',
    'Taif',
    'Najran',
    'Qatif',
    'Abha',
    'Yanbu',
    'Al Kharj',
    'Sakaka',
    'Jizan',
    'Qurayyat',
    'Dhuba',
    'Rabigh',
    'Mahd Al-Dhahab',
    'Al-Bahah',
    'Bisha',
    'Unaizah',
    'Ar Rass',
    'Arar',
    'Tarout',
    'Qaisumah',
    'Al-Mubarraz',
    'Ras Tanura',
    'Rahima',
    'Al Majma\'ah',
    'Al-Ahsa',
    'Safwa',
    'Sihat',
    'Al-Zulfi',
    'Rafha',
    'Riyadh Al-Khabra',
    'Al-Bukayriyah',
    'Shaqraa',
    'Al-Mithnab',
    'Al-Ghat',
    'Afif',
    'Al-Dawadimi',
    'Layla',
    'Al-Artawiya',
    'As-Sulayyil',
    'Wadi ad-Dawasir',
    'Al-Kharj',
    'Al-Aflaj',
    'Al-Hotah',
    'Haradh',
    'Thadiq',
    'Rumah',
    'Marrat',
    'Harmah',
    'Hawtat Sudair',
    'Majmaah',
    'Ghat',
    'Zulfi',
    'Shaqra',
    'Durma',
    'Marat',
    'Al-Gway\'iyyah',
    'Afif',
    'Al-Dawadmi',
    'Layla',
    'Al-Quway\'iyyah',
    'Wadi Al-Dawasir',
    'As-Sulayyil',
    'Aflaj',
    'Hotat Bani Tamim',
    'Al-Hariq',
    'Al-Muzahimiyah',
    'Dhurma',
    'Huraymila',
    'Thadiq',
    'Rumah',
    'Marrat',
    'Harmah',
    'Hawtat Sudair',
    'Majmaah',
    'Ghat',
    'Zulfi',
    'Shaqra',
    'Durma',
    'Al-Gway\'iyyah',
    'Afif',
    'Al-Dawadmi',
    'Layla',
    'Al-Quway\'iyyah',
    'Wadi Al-Dawasir',
    'As-Sulayyil',
    'Aflaj',
    'Hotat Bani Tamim',
    'Al-Hariq',
    'Al-Muzahimiyah',
    'Dhurma',
    'Huraymila'
  ];

  // Filter cities based on search query
  static List<String> filterCities(String query) {
    if (query.isEmpty) return [];

    return cities
        .where((city) => city.toLowerCase().contains(query.toLowerCase()))
        .toList();
  }
}
